### ISSUE TITLE
It doesn't wok here and creates no log file

### ISSUE THREAD

**Issue by Parisa-b** [SublimeCodeIntel/SublimeCodeIntel#408]
After installing it on Sublime2 and getting package manager message regarding that it was installed successfully I restarted sublime but only got the default auto completion afterwards, Disabled the default auto completion and still nothing it has no log file or db in .codeintel .

**Comment by Kronuz** [comment]
The possible answer is addressed in the Tronleshooting part of the README (as "Ignored package?")

**Comment by apzentral** [comment]
I also have the same problem. I checked Ignored package location and it still doesn't generate .codeintel for me.

**Comment by Kronuz** [comment]
It's possible you need to close and reopen sublime text as well as the file you are editing. Let me know if that works for you as I think I'm identifying a bug that causes that behavior.

**Comment by apzentral** [comment]
I closed and re-open, just to mention that the Sublime Detect the Slow Plugin which is SublimeCodeIntel and I think it kill the process. Hope this will help you identify the problem.
