### ISSUE TITLE
100% CPU usage when a directory is open with ST2

### ISSUE THREAD

**Issue by dorian-marchal** [SublimeCodeIntel/SublimeCodeIntel#468]
SublimeCodeIntel takes 100% of the CPU when there is a directory in the project (even if the directory is empty).

~~I ran a `git bisect` on the repo and found that 07f8720680d20c2f89e1d93942bd986e8758142b introduced this behaviour.~~

~~Everything is fine if I checkout `master` and remove `.decode('utf-8')` on lines
1247 : https://github.com/SublimeCodeIntel/SublimeCodeIntel/blob/master/SublimeCodeIntel.py#L1247
1256 : https://github.com/SublimeCodeIntel/SublimeCodeIntel/blob/master/SublimeCodeIntel.py#L1256~~

_[Edit : this commit did not produce the error, it was just fixing one that prevented SCI from working (so no slowness if SCI is not working :sweat_smile: ) ]_

**More infos :**
- Sublime Text 2.0.2 (build 2221)
- It takes 100% CPU only when I'm typing
- This is sufficient to produce the slowness :
  - Launch ST with no project open, 
  - drag'n'drop an an empty folder in the left bar
  - start typing -> 100% CPU
- No entries in the log file
- Happens with every filetypes (even Plain text)
- Typing in the Sublime Text console is also very slow
- I tried to remove `~/codeintel` : no change

I hope this is enough to help you fix this bug :+1:

**Comment by Kronuz** [comment]
Must be a problem with one of the files in the folder you dragged. Can you please share the `Session.sublime_session` and `Auto Save Session.sublime_session` in your `Packages/../Settings` directory when this happens? ..or otherwise send me a `repr(data)`

**Comment by dorian-marchal** [comment]
The folder I dragged was an empty one (freshly created).

`Session.sublime_session` : https://gist.github.com/dorian-marchal/12265df0e92a8e6ce1bb
I don't have any `Auto Save Session.sublime_session`

**Comment by dorian-marchal** [comment]
Deleted my `Session.sublime_session`.
This seems to have fixed the problem.

**Comment by nietonfir** [comment]
@dorian-marchal What about creating a new project or opening an existing one? After removing the session file everything was running normal for me as well, but opening a project (symfony2 - PHP, Twig, CSS, JS) reintroduced the unresponsivness immediately with the errors showing up in the console mentioned by @etienned in #460.

**Comment by dorian-marchal** [comment]
Actually, you're right, I have an error when opening an existing project and the slowness reappear.

My error is different, though :

```js
Traceback (most recent call last):
  File "./sublime_plugin.py", line 236, in on_query_completions
  File "./SublimeCodeIntel.py", line 1568, in on_query_completions
    word_completions_from_buffer = wordsFromBufferMgr.getCompletions(view, prefix, locations, add_word_completions)
  File "./SublimeCodeIntel.py", line 1128, in getCompletions
    words = self.fix_truncation(view, words)
  File "./SublimeCodeIntel.py", line 1158, in fix_truncation
    truncated = self.is_empty_match(match)
  File "./SublimeCodeIntel.py", line 1182, in is_empty_match
    return match.empty()
AttributeError: 'NoneType' object has no attribute 'empty'
```

**Comment by Kronuz** [comment]
This is a second unrelated bug... it seems heating bugs in Sublime Text 2 which throw exceptions make the whole editor slow for some reason. I'm checking both problems and hopefully fix them

**Comment by Kronuz** [comment]
This should be fixed in master... hopefully. I'll push a new release right now (v2.1.6) with quite a few changes and optimizations.

**Comment by wizza-smile** [comment]
Dude, don't forget to advert **SublimeCodeIntel3** !

**Comment by dorian-marchal** [comment]
Nope, not fixed.
Tried 153faab9492f3, still as slow.

Actually, this problem was already present in the v2.1.2.
And like the v2.1.1 wasn't working (`'UnicodeDecodeError')
I don't know where this bug first appears.

The v2.1.0 is the last one that works well for me.

**Comment by Kronuz** [comment]
The settings manager is the one which makes Sublime Text say the on_modified is slow, when it starts. As for the general slowness after that, I think project_name and project_data implementations could be really slow. We might need to rework those.

**Comment by wizza-smile** [comment]
I fixed this issue properly. I noticed that the whole thing was not running well in v2.1.7 still. 
The project-file is never opened and so non of the project specific settings will work. The implementation had to be changed to run smoothly on ST2.

I uploaded this as a new project, find it here:
https://github.com/spectacles/CodeComplice

Be sure to check out the correct branch for ST2!
