### ISSUE TITLE
PermissionError : [WinError 5] Permission denied

### ISSUE THREAD

**Issue by guilty80** [SublimeCodeIntel/SublimeCodeIntel#527]
Hi guys,

I'm trying to use SublimeCodeIntel for symfony2 project.
But i doesn't work, so i've searched on readme and issues and found more questions than answer.
I thought i found the answer on this [issue](https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/366) but it seems to be a linux specific help because in my Sublime Project folder, i don't have a .codeintel folder there but in my C:\Users\%UserName% folder. Hope you'll be able to help me.

Sublime Text version : 3 (build 3083)
Plateform : Windows 7(64bits)
Language : PHP

Error log : 
```
Starting logging SublimeCodeIntel v2.2.0 rev GIT-unknown (1435752208) on Wed Jul  1 14:09:00 2015
=================================================================================================
Updating indexes for 'PHP'... The first time this can take a while.
scan_purelang: path: 'C:\\wamp\\www\\pdfgen\\src\\OC\\PdfgenBundle\\Controller\\UsersController.php' lang: PHP
Doing CodeIntel for 'PHP' (hold on)...
Done 'PHP' CodeIntel! Full CodeIntel took 328ms
Doing CodeIntel for 'PHP' (hold on)...
eval 'u' at UsersController.php#12  <Trigger 'php-complete-variables' at 254>
variable_names_from_scope_starting_with_expr:: expr: None, scoperef: (<Element 'scope' at 0x0000000003FB6EB8>, ['OC\\PdfgenBundle\\Controller', 'UsersController', 'GetUsersAction']) for ('locals', 'builtins')
variable_names_from_scope_starting_with_expr:: adding locals: ['users']
Unexpected error with evaluator: 'u' at UsersController.php#12
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
PermissionError: [WinError 5] Accès refusé

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Guilty\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree.py", line 317, in eval
    cplns = self.eval_cplns()
  File "C:\Users\Guilty\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree_php.py", line 220, in eval_cplns
    return self._variables_from_scope(self.expr, start_scope)
  File "C:\Users\Guilty\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree_php.py", line 481, in _variables_from_scope
    self.variable_names_from_elem)
  File "C:\Users\Guilty\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree_php.py", line 422, in _element_names_from_scope_starting_with_expr
    lib = self.buf.stdlib
  File "C:\Users\Guilty\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_php.py", line 1304, in stdlib
    return self.libs[-1]
  File "C:\Users\Guilty\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_php.py", line 1300, in libs
    return self.langintel.libs_from_buf(self)
  File "C:\Users\Guilty\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_php.py", line 1008, in libs_from_buf
    libs += self._buf_indep_libs_from_env(env)
  File "C:\Users\Guilty\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_php.py", line 1158, in _buf_indep_libs_from_env
    = self._php_info_from_php(php, env)
  File "C:\Users\Guilty\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_php.py", line 1061, in _php_info_from_php
    p = process.ProcessOpen(argv, env=env.get_all_envvars())
  File "C:\Users\Guilty\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\process.py", line 357, in __init__
    creationflags=flags)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
PermissionError: [WinError 5] Accès refusé
done eval: eval error
Done 'PHP' CodeIntel! Full CodeIntel took 10ms
Doing CodeIntel for 'PHP' (hold on)...
```
config files : 
      SublimeCodeIntel.sublime-settings -- Default : untouched
      SublimeCodeIntel.sublime-settings -- User : 
```
/*
   SublimeCodeIntel default settings
   All settings can be overridden in *.sublime-project file
*/
{
    /*
       Sets the mode in which SublimeCodeIntel runs:

       true - Enabled (the default).
       false - Disabled.
    */
    "codeintel": true,

    /* path to codeintel database */
    "codeintel_database_dir": "~/.codeintel",

    /*
       An array of language names which are enabled.
    */
    "codeintel_enabled_languages":
    [
       "JavaScript", "SCSS", "Python", "HTML",
       "Ruby", "Python3", "XML", "Sass", "HTML5", "Perl", "CSS",
       "Twig", "Less", "Node.js", "TemplateToolkit", "PHP"
    ],

    /*
       Maps syntax names to languages. This allows variations on a syntax
       (for example "Python (Django)") to be used. The key is
       the base filename of the .tmLanguage syntax files, and the value
       is the syntax it maps to.
    */
    "codeintel_syntax_map":
    {
       "Python Django": "Python"
    },


    /* ####################################################################### */
    /* the following settings can be overridden for each language individually */
    /* see "codeintel_language_settings" below!                                */
    /* ####################################################################### */

    /*
       Sets the mode in which SublimeCodeIntel's live autocomplete runs:

       true - Autocomplete popups as you type (the default).
       false - Autocomplete popups only when you request it.
    */
    "codeintel_live": true,

    /*
       Tooltips method:

       "popup" - Uses Autocomplete popup for tooltips.
       "panel" - Uses the output panel for tooltips.
       "status" - Uses the status bar for tooltips (was the default).
    */
    "codeintel_tooltips": "popup",


    /*
       "buffer" - add word completions from current view
       "all" - add word completions from all views from active window
       "none" - do not add word completions
    */
    "codeintel_word_completions": "buffer",

    /*
       Insert functions snippets.
    */
    "codeintel_snippets": true,

    /*
       Define global filters to exclude paths from scanning. Use the codeintel_config setting for language specific settings.
       ex: ["list/of","/path/to/exclude"]
       (Currently only working for JavaScript and PHP)
    */
    "codeintel_scan_exclude_dir":[],

    /* Code Scanning: Controls how the Code Intelligence system scans your source code files. */

    /* Maximum directory depth: */
    "codeintel_max_recursive_dir_depth": 25,

    /* Include all files and directories from the project base directory: */
    "codeintel_scan_files_in_project": true,

    /* API Catalogs: SublimeCodeIntel uses API catalogs to provide autocomplete and calltips for 3rd-party libraries.
      Add te libraries that you use in your code. Note: Adding all API catalogs for a particular language can lead to confusing results.

      Avaliable catalogs:
           PyWin32 (Python3) (for Python3: Python Extensions for Windows)
           PyWin32 (for Python: Python Extensions for Windows)
           Rails (for Ruby: Rails version 1.1.6)
           jQuery (for JavaScript: jQuery JavaScript library - version 1.9.1)
           Prototype (for JavaScript: JavaScript framework for web development)
           dojo (for JavaScript: Dojo Toolkit API - version 1.5.0)
           Ext_30 (for JavaScript: Ext JavaScript framework - version 3.0)
           HTML5 (for JavaScript: HTML5 (Canvas, Web Messaging, Microdata))
           MochiKit (for JavaScript: A lightweight JavaScript library - v1.4.2)
           Mozilla Toolkit (for JavaScript: Mozilla Toolkit API - version 1.8)
           XBL (for JavaScript: XBL JavaScript support - version 1.0)
           YUI (for JavaScript: Yahoo! User Interface Library - v2.8.1)
           Drupal (for PHP: A full-featured PHP content management/discussion engine -- v5.1)
           PECL (for PHP: A collection of PHP Extensions)
    */
    "codeintel_selected_catalogs": [],

    /*
        When editing within a defined scope, no live completion will trigger. ex: ["comment"]
     */
    "codeintel_exclude_scopes_from_complete_triggers": ["comment"],

    /*
       Defines a configuration for each language.
    */
    "codeintel_language_settings": {
        "Python3": {
            "python3": "/usr/local/bin/python3.3",
            "codeintel_scan_extra_dir": [
                "/Applications/Sublime Text.app/Contents/MacOS",
                "~/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/arch",
                "~/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs"
            ],
            "codeintel_scan_files_in_project": true,
            "codeintel_selected_catalogs": []
        },
        "JavaScript": {
            "codeintel_scan_extra_dir": [],
            "codeintel_scan_exclude_dir":["/build/", "/min/"],
            "codeintel_scan_files_in_project": false,
            "codeintel_max_recursive_dir_depth": 2,
            "codeintel_selected_catalogs": ["jQuery"]
        },
        "PHP": {
            "php": "C:\\wamp\\bin\\php\\php5.4.16",
            "codeintel_scan_extra_dir": [],
            "codeintel_scan_files_in_project": true,
            "codeintel_max_recursive_dir_depth": 25,
            "codeintel_scan_exclude_dir":["/Applications/MAMP/bin/php/php5.5.3/"]
        }
    }
}
```

**Comment by guilty80** [comment]
Resolved as my path to python wasn't changed in config file (maybe add on install steps that it require to have python path in config setup to make it work

**Comment by leobastiani** [comment]
how did you fix?

**Comment by ZiperRom1** [comment]
same error, where did you put python path ? which one (2.7 or 3.5 ) ?
I tried to put my python 3 path in

```json
"codeintel_language_settings": {
        "Python3": {
            "python3": "my\\python3\\path
        }
    }
```

But the bug is still there

**Comment by ZiperRom1** [comment]
Fix: need full path to the executable file for python and php config (your/path/to/python.exe and your/path/to/php.exe)

**Comment by leobastiani** [comment]
thank you

**Comment by leobastiani** [comment]
thank you
did you put python 2 or 3?

**Comment by ZiperRom1** [comment]
both

**Comment by ZiperRom1** [comment]
with double backslash in the path

```json
"codeintel_language_settings": {
        "Python": {
            "python": "C:\\Program Files (x86)\\Python 2.7\\python.exe"
        },
        "Python3": {
            "python3": "C:\\Program Files (x86)\\Python 3.5\\python.exe",
            "codeintel_scan_extra_dir": [
                "~/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/arch",
                "~/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs"
            ],
            "codeintel_scan_files_in_project": true,
            "codeintel_selected_catalogs": []
        },
        "JavaScript": {
            "codeintel_scan_extra_dir": [],
            "codeintel_scan_exclude_dir":["/build/", "/min/", "/dist/"],
            "codeintel_scan_files_in_project": true,
            "codeintel_max_recursive_dir_depth": 5,
            "codeintel_selected_catalogs": ["jQuery"]
        },
        "PHP": {
            "php": "C:\\Program Files\\php\\php.exe",
            "phpConfigFile": "C:\\Program Files\\php\\php.ini",
            "codeintel_scan_extra_dir": ["C:\\prog\\web\\php"],
            "codeintel_scan_files_in_project": true,
            "codeintel_max_recursive_dir_depth": 20,
            "codeintel_scan_exclude_dir":[]
        }
    }
```
